export enum AuthorizationErrorCode {
  FORBIDDEN = 'AUTHORIZATION_FORBIDDEN',
  INSUFFICIENT_PERMISSIONS = 'AUTHORIZATION_INSUFFICIENT_PERMISSIONS',
  INSUFFICIENT_ROLE = 'AUTHORIZATION_INSUFFICIENT_ROLE',
}
