export enum InfrastructureErrorCode {
  GENERIC = 'INFRASTRUCTURE_ERROR',
  DATABASE_ERROR = 'INFRASTRUCTURE_DATABASE_ERROR',
  CACHE_ERROR = 'INFRASTRUCTURE_CACHE_ERROR',
  QUEUE_ERROR = 'INFRASTRUCTURE_QUEUE_ERROR',
  STORAGE_ERROR = 'INFRASTRUCTURE_STORAGE_ERROR',
  EXTERNAL_SERVICE_ERROR = 'INFRASTRUCTURE_EXTERNAL_SERVICE_ERROR',
}
