export enum SystemErrorCode {
  NOT_FOUND = 'SYSTEM_NOT_FOUND',
  CONFLICT = 'SYSTEM_CONFLICT',
  RATE_LIMITED = 'SYSTEM_RATE_LIMITED',
  SERVICE_UNAVAILABLE = 'SYSTEM_SERVICE_UNAVAILABLE',
  INTERNAL_ERROR = 'SYSTEM_INTERNAL_ERROR',
}
