import type { ExtractedFileMetadata } from '../utils/extract-file-metadata';
import type { Media } from '../types/media';

export type UploadQueueItemStatus =
  | 'pending'
  | 'requesting'
  | 'uploading'
  | 'confirming'
  | 'processing'
  | 'success'
  | 'error'
  | 'canceled';

/**
 * One locally-queued file awaiting real upload (Milestone 5). `storageKey`
 * no longer exists here — it's server-generated by
 * `POST /media/upload-requests` from the sanitized filename, never
 * user-entered. `abortController` backs real cancel of the in-flight
 * upload-request/PUT/confirm sequence; `progress` is real byte-level
 * progress (0–100) during the `uploading` status, sourced from
 * `XMLHttpRequest.upload.onprogress` (`media-upload.service.ts`).
 */
export interface UploadQueueItem {
  localId: string;
  file: File;
  previewUrl: string | null;
  metadata: ExtractedFileMetadata;
  mediaAssetId: string | null;
  folderId: string;
  altText: string;
  caption: string;
  credit: string;
  status: UploadQueueItemStatus;
  progress: number;
  errorMessage: string | null;
  result: Media | null;
  abortController: AbortController | null;
}
