import {
  Type,
  Heading,
  Image,
  Images,
  Video,
  Youtube,
  Quote,
  Minus,
  Table,
  Code,
  FileCode,
  Link,
  MousePointerClick,
  Megaphone,
  AlertTriangle,
  List,
  ListChecks,
  ChevronsUpDown,
  PanelTop,
  Download,
  MoveVertical,
  Columns,
  Square,
  Repeat,
} from 'lucide-react';
import type { BlockDefinition, BlockFieldDescriptor } from './block-definition.types';

const listOf = (
  itemFields: BlockFieldDescriptor[]
): Pick<BlockFieldDescriptor, 'kind' | 'itemFields'> => ({
  kind: 'list',
  itemFields,
});

/**
 * The 25 built-in block definitions — mirrors the backend's
 * `BLOCK_TYPE_DESCRIPTORS` field-for-field
 * (`apps/backend/src/modules/content-blocks/block-schema/block-types.ts`),
 * extended with an `icon` (block picker) and `defaultData` (seed value
 * when a block is inserted). Registered into the open registry by
 * `block-registry.ts` at module load — see that file's doc comment for
 * why they're not hardcoded directly into the registry map.
 */
export const BUILT_IN_BLOCK_DEFINITIONS: BlockDefinition[] = [
  {
    type: 'paragraph',
    label: 'Paragraph',
    family: 'leaf',
    container: false,
    icon: Type,
    description: 'A block of body text.',
    fields: [{ key: 'text', label: 'Text', kind: 'richtext', required: true }],
    defaultData: { text: '' },
  },
  {
    type: 'heading',
    label: 'Heading',
    family: 'leaf',
    container: false,
    icon: Heading,
    description: 'A section heading, H1 through H6.',
    fields: [
      { key: 'text', label: 'Text', kind: 'text', required: true },
      {
        key: 'level',
        label: 'Level',
        kind: 'select',
        required: true,
        defaultValue: '2',
        options: [1, 2, 3, 4, 5, 6].map((n) => ({ value: String(n), label: `H${n}` })),
      },
    ],
    defaultData: { text: '', level: '2' },
  },
  {
    type: 'image',
    label: 'Image',
    family: 'media',
    container: false,
    icon: Image,
    description: 'A single image with alt text and an optional caption.',
    fields: [
      { key: 'url', label: 'Image URL', kind: 'url', required: true },
      { key: 'alt', label: 'Alt text', kind: 'text', required: true },
      { key: 'caption', label: 'Caption', kind: 'text' },
    ],
    defaultData: { url: '', alt: '' },
  },
  {
    type: 'gallery',
    label: 'Gallery',
    family: 'media',
    container: false,
    icon: Images,
    description: 'A grid of multiple images.',
    fields: [
      {
        key: 'images',
        label: 'Images',
        ...listOf([
          { key: 'url', label: 'Image URL', kind: 'url', required: true },
          { key: 'alt', label: 'Alt text', kind: 'text', required: true },
          { key: 'caption', label: 'Caption', kind: 'text' },
        ]),
      },
    ],
    defaultData: { images: [] },
  },
  {
    type: 'video',
    label: 'Video',
    family: 'media',
    container: false,
    icon: Video,
    description: 'A self-hosted / direct-link video file.',
    fields: [
      { key: 'url', label: 'Video URL', kind: 'url', required: true },
      { key: 'poster', label: 'Poster image URL', kind: 'url' },
      { key: 'caption', label: 'Caption', kind: 'text' },
    ],
    defaultData: { url: '' },
  },
  {
    type: 'youtube',
    label: 'YouTube',
    family: 'media',
    container: false,
    icon: Youtube,
    description: 'An embedded YouTube video.',
    fields: [
      { key: 'videoId', label: 'YouTube video ID', kind: 'text', required: true },
      { key: 'caption', label: 'Caption', kind: 'text' },
    ],
    defaultData: { videoId: '' },
  },
  {
    type: 'vimeo',
    label: 'Vimeo',
    family: 'media',
    container: false,
    icon: Video,
    description: 'An embedded Vimeo video.',
    fields: [
      { key: 'videoId', label: 'Vimeo video ID', kind: 'text', required: true },
      { key: 'caption', label: 'Caption', kind: 'text' },
    ],
    defaultData: { videoId: '' },
  },
  {
    type: 'quote',
    label: 'Quote',
    family: 'leaf',
    container: false,
    icon: Quote,
    description: 'A block quotation with an optional citation.',
    fields: [
      { key: 'text', label: 'Quote', kind: 'richtext', required: true },
      { key: 'citation', label: 'Citation', kind: 'text' },
    ],
    defaultData: { text: '' },
  },
  {
    type: 'divider',
    label: 'Divider',
    family: 'leaf',
    container: false,
    icon: Minus,
    description: 'A horizontal rule separating content.',
    fields: [],
    defaultData: {},
  },
  {
    type: 'table',
    label: 'Table',
    family: 'rich',
    container: false,
    icon: Table,
    description: 'A data table with header and body rows.',
    fields: [
      {
        key: 'headers',
        label: 'Header cells',
        ...listOf([{ key: 'text', label: 'Text', kind: 'text', required: true }]),
      },
      {
        key: 'rows',
        label: 'Rows',
        ...listOf([
          {
            key: 'cells',
            label: 'Cells',
            ...listOf([{ key: 'text', label: 'Text', kind: 'text', required: true }]),
          },
        ]),
      },
    ],
    defaultData: { headers: [], rows: [] },
  },
  {
    type: 'code-block',
    label: 'Code block',
    family: 'rich',
    container: false,
    icon: Code,
    description: 'A syntax-highlighted code snippet.',
    fields: [
      { key: 'code', label: 'Code', kind: 'textarea', required: true },
      { key: 'language', label: 'Language', kind: 'text', placeholder: 'e.g. typescript' },
    ],
    defaultData: { code: '' },
  },
  {
    type: 'html-block',
    label: 'HTML block',
    family: 'rich',
    container: false,
    icon: FileCode,
    description: 'Raw HTML — sanitized server-side against an allow-list before it is ever stored.',
    fields: [{ key: 'html', label: 'HTML', kind: 'textarea', required: true }],
    defaultData: { html: '' },
  },
  {
    type: 'embed',
    label: 'Embed',
    family: 'rich',
    container: false,
    icon: Link,
    description: 'A generic sandboxed iframe embed (e.g. a map, a tweet, a form).',
    fields: [
      { key: 'url', label: 'Embed URL', kind: 'url', required: true },
      { key: 'caption', label: 'Caption', kind: 'text' },
    ],
    defaultData: { url: '' },
  },
  {
    type: 'button',
    label: 'Button',
    family: 'action',
    container: false,
    icon: MousePointerClick,
    description: 'A call-to-action link styled as a button.',
    fields: [
      { key: 'label', label: 'Label', kind: 'text', required: true },
      { key: 'url', label: 'URL', kind: 'url', required: true },
      {
        key: 'style',
        label: 'Style',
        kind: 'select',
        defaultValue: 'primary',
        options: ['primary', 'secondary', 'outline', 'ghost'].map((v) => ({ value: v, label: v })),
      },
      { key: 'openInNewTab', label: 'Open in new tab', kind: 'boolean', defaultValue: false },
    ],
    defaultData: { label: '', url: '', style: 'primary', openInNewTab: false },
  },
  {
    type: 'callout',
    label: 'Callout',
    family: 'action',
    container: false,
    icon: Megaphone,
    description: 'A highlighted note box.',
    fields: [
      { key: 'title', label: 'Title', kind: 'text' },
      { key: 'text', label: 'Text', kind: 'richtext', required: true },
      {
        key: 'tone',
        label: 'Tone',
        kind: 'select',
        defaultValue: 'info',
        options: ['info', 'success', 'warning'].map((v) => ({ value: v, label: v })),
      },
    ],
    defaultData: { text: '', tone: 'info' },
  },
  {
    type: 'alert',
    label: 'Alert',
    family: 'action',
    container: false,
    icon: AlertTriangle,
    description: 'A prominent status message.',
    fields: [
      { key: 'text', label: 'Text', kind: 'richtext', required: true },
      {
        key: 'tone',
        label: 'Tone',
        kind: 'select',
        required: true,
        defaultValue: 'info',
        options: ['info', 'success', 'warning', 'critical'].map((v) => ({ value: v, label: v })),
      },
    ],
    defaultData: { text: '', tone: 'info' },
  },
  {
    type: 'list',
    label: 'List',
    family: 'leaf',
    container: false,
    icon: List,
    description: 'An ordered or unordered list.',
    fields: [
      {
        key: 'style',
        label: 'Style',
        kind: 'select',
        required: true,
        defaultValue: 'unordered',
        options: [
          { value: 'unordered', label: 'Bulleted' },
          { value: 'ordered', label: 'Numbered' },
        ],
      },
      {
        key: 'items',
        label: 'Items',
        ...listOf([{ key: 'text', label: 'Text', kind: 'text', required: true }]),
      },
    ],
    defaultData: { style: 'unordered', items: [] },
  },
  {
    type: 'checklist',
    label: 'Checklist',
    family: 'leaf',
    container: false,
    icon: ListChecks,
    description: 'A list of checked/unchecked items.',
    fields: [
      {
        key: 'items',
        label: 'Items',
        ...listOf([
          { key: 'text', label: 'Text', kind: 'text', required: true },
          { key: 'checked', label: 'Checked', kind: 'boolean', defaultValue: false },
        ]),
      },
    ],
    defaultData: { items: [] },
  },
  {
    type: 'accordion',
    label: 'Accordion',
    family: 'container',
    container: true,
    icon: ChevronsUpDown,
    description: 'Collapsible panels. Add child blocks and assign each to a panel.',
    fields: [
      {
        key: 'panels',
        label: 'Panels',
        ...listOf([{ key: 'title', label: 'Panel title', kind: 'text', required: true }]),
      },
    ],
    defaultData: { panels: [{ title: 'Panel 1' }] },
  },
  {
    type: 'tabs',
    label: 'Tabs',
    family: 'container',
    container: true,
    icon: PanelTop,
    description: 'Tabbed panels. Add child blocks and assign each to a tab.',
    fields: [
      {
        key: 'tabs',
        label: 'Tabs',
        ...listOf([{ key: 'label', label: 'Tab label', kind: 'text', required: true }]),
      },
    ],
    defaultData: { tabs: [{ label: 'Tab 1' }] },
  },
  {
    type: 'file-download',
    label: 'File download',
    family: 'media',
    container: false,
    icon: Download,
    description: 'A downloadable file link.',
    fields: [
      { key: 'url', label: 'File URL', kind: 'url', required: true },
      { key: 'filename', label: 'Display filename', kind: 'text' },
      {
        key: 'filesize',
        label: 'File size (display text)',
        kind: 'text',
        placeholder: 'e.g. 2.4 MB',
      },
    ],
    defaultData: { url: '' },
  },
  {
    type: 'spacer',
    label: 'Spacer',
    family: 'leaf',
    container: false,
    icon: MoveVertical,
    description: 'Vertical whitespace.',
    fields: [
      { key: 'height', label: 'Height (px)', kind: 'number', required: true, defaultValue: 40 },
    ],
    defaultData: { height: 40 },
  },
  {
    type: 'columns',
    label: 'Columns',
    family: 'container',
    container: true,
    icon: Columns,
    description: 'A multi-column layout. Add child blocks and assign each to a column.',
    fields: [
      {
        key: 'columnCount',
        label: 'Number of columns',
        kind: 'select',
        required: true,
        defaultValue: '2',
        options: ['2', '3', '4'].map((v) => ({ value: v, label: v })),
      },
    ],
    defaultData: { columnCount: '2' },
  },
  {
    type: 'container',
    label: 'Container',
    family: 'container',
    container: true,
    icon: Square,
    description: 'A section wrapper with width/background/padding controls around its children.',
    fields: [
      {
        key: 'maxWidth',
        label: 'Max width',
        kind: 'select',
        defaultValue: 'normal',
        options: ['narrow', 'normal', 'wide', 'full'].map((v) => ({ value: v, label: v })),
      },
      { key: 'background', label: 'Background color', kind: 'color' },
      {
        key: 'padding',
        label: 'Padding',
        kind: 'select',
        defaultValue: 'md',
        options: ['none', 'sm', 'md', 'lg'].map((v) => ({ value: v, label: v })),
      },
    ],
    defaultData: { maxWidth: 'normal', padding: 'md' },
  },
  {
    type: 'reusable-block',
    label: 'Reusable block',
    family: 'reference',
    container: false,
    icon: Repeat,
    description: 'Insert a block from the Reusable Blocks library by reference.',
    fields: [
      {
        key: 'reusableBlockId',
        label: 'Reusable block',
        kind: 'reusable-block-ref',
        required: true,
      },
    ],
    defaultData: { reusableBlockId: '' },
  },
];
