export enum SeoWarningCode {
  TITLE_MISSING = 'TITLE_MISSING',
  TITLE_TOO_SHORT = 'TITLE_TOO_SHORT',
  TITLE_TOO_LONG = 'TITLE_TOO_LONG',
  DESCRIPTION_MISSING = 'DESCRIPTION_MISSING',
  DESCRIPTION_TOO_SHORT = 'DESCRIPTION_TOO_SHORT',
  DESCRIPTION_TOO_LONG = 'DESCRIPTION_TOO_LONG',
  CANONICAL_MISSING = 'CANONICAL_MISSING',
  IMAGE_MISSING = 'IMAGE_MISSING',
  ROBOTS_INVALID = 'ROBOTS_INVALID',
}

export interface SeoWarning {
  code: SeoWarningCode;
  field: string;
  message: string;
}
